### ISSUE TITLE
윤영서 코드리뷰입니다.

### ISSUE THREAD

**Issue by YeongseoYoon** [rae-han/assignment-pomodoro#1]
1. 
```  const onClick = () => {
    if (rounds === 4 * 12) {
      return;
    }
    setIsRunning((prev) => !prev);
  };
  ``` 
이부분 너무 재밌었어요! 저는 그냥 0으로 리셋시켜 버렸는데 래한님은 그냥 클릭을 동작하지 못하게 해버리셨네요 ㅎㅎ
  
  2. 컴포넌트 분리하신 부분도 너무 깔끔하네요!! 와웅 이부분은 진짜 배우고 갑니다 멋져요

**Comment by rae-han** [comment]
@YeongseoYoon 감사합니다!!
